# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b6747961f10c7644680fd12618bbb87aa8493f2d6245b52ec2727c77446267b969ab27ff9623804d505a379d9773225196f7f5bea72f7e2217885f1cdb1611c

test:
  secret_key_base: 99c124466ba753c7fc7e8b775b59782be22cbf1158828c92583f36c27efba2782690b7a6f330369f7095a0598211008741bfc01a4b50b95c1d30cad9dfe01836

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
